release
Kaminari26/java-filmorate pull request #12
Opened 2023-03-12 09:56 UTC by Kaminari26

2023-03-13 07:51 UTC, YazykovMikhail requested changes

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
Посмотри в чем разница между
@notblank и https://github.com/NotNull
и оставь что то одно

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    String name;
перевод строки

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull
@NotBlank

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +            throw new ValidationException("500");
ты передаешь сообщение 500, в сообщении стоит передавать еральное описание проблемы

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/validationExeption/ValidationException.java
> +public class ValidationException extends Throwable {
extends RuntimeExceeption

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws ValidationException {
throws ValidationException рпокидывать не надо, потому что исключение будет наследоваться от RuntimeException.
касается всех эндпоинтов
всех контроллеров

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +    LocalDate movieBirthday = LocalDate.of(1895,12,28);
public static final
и так же название сделай в соотвествении со статичными переменнами

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +        return  filmMap.values();
лишний пробел

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +@Slf4j
в контроллерах как минимум нудно делать лргирвоание такого характера
- в самом начале
Пришел запрос аткой то: тело запроса
- в самом конце
Ответ отправлен: тело ответа

Касается обоих контроллеров

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +        } else {
не нужно делать иначе, убри блок иначе а код оставь.

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public int filmId() {
этот метож долежн быть в контроллерее. одель данных не может отвечать за генерацию или хранения id

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +        if (filmMap.containsKey(film.getId())) {
if (!filmMap.containsKey(film.getId())) {
  throw new RuntimeException("500"); 
        } 
        filmMap.put(film.getId(), film);
            log.info("Фильм " + film.getName() + " обновлен");
            return film;

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +            throw new RuntimeException("500");
ты отправялешь код своему тимлиду что бы он ушел продакшен. Соообщение 500 не очень

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +    int userId = 1;
модификатор доступа

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +        user.setId(userId);
user.setId(++userId); можно вот так
а userId +=1; убрать

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +    int userId = 1;
назови лучше counter
Также счетчик id в этом контролле у тебя тут, а в предыдушем в модели. 
Даже если оба вариант не правильные, стоит делать все единообразно.
А так в FilmController сделай такой же счетчик

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +            user.setName(user.getLogin());
сделай тут логирвоание, произошло какое то бизнес действие, стоит это залоогировать

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +            if(user.getName() == null){
пропушен пробел

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +    public Collection<User> getUsersList(){
пропушен пробел

2023-03-13 07:51 UTC, YazykovMikhail commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Из задания:
Тестирование
Добавьте тесты для валидации. Убедитесь, что она работает на граничных условиях.
Даже если пока не умеешь тестировать spring приложения, то какую то логику и какую то валидацию которая сделана не через аннотация протестировать все равно можно

2023-03-13 07:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +        throw new RuntimeException("500");
сначала проверяй
 if (!users.containsKey(user.getId()))  и выбрасывай исключение
 а потом идет основной код бизнес логики

2023-03-13 21:17 UTC, Kaminari26 commented
Понял про информативные коммиты только после того, как залил(( перезаливать не буду, но в следующий раз сделаю как надо все. Почему то думал что описать проделанную работу нужно будет где то здесь

2023-03-14 14:29 UTC, YazykovMikhail approved these changes
Что то поправил, что то нет. Я задачу приму, Только в следующей работе все поправь.

2023-03-14 14:29 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +   private int id;
разметка(отступ), должен быть tab(4 пробела) 

Проверь во всем классе

2023-03-14 14:29 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String name;
Модификатор доступа

2023-03-14 14:29 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) {
продублирую замечание по поводу else, лучше делать вот так:

@PostMapping
    public Film create(@Valid @RequestBody Film film) {
        log.info("Запрошено добавление фильма " + film);
        if (film.getReleaseDate().isBefore(MOVIE_BIRTHDAY)) {
            log.warn("Неверно указана дата релиза" + film.getName());
            throw new ValidationException("Произошла ошибка при попытке создания фильма");
        }
        film.setId(++counter);
        filmMap.put(film.getId(), film);
        log.info("Фильм " + film.getName() + " добавлен.");
        return film;
    }
    без else в таких ситуациях

2023-03-14 14:29 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +            log.warn("Неверно указана дата релиза" + film.getName());
это уже не предупреждение, это ошибка
log.error

2023-03-14 14:29 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +            if(user.getName() == null) {
разметка

2023-03-14 14:29 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +            user.setName(user.getLogin());
Не исправдено
Так же и в нижнем методе

2023-03-14 14:29 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +        return users.values();
стоит добавить логирвоание
Как узнать что запрос вообще приходил? И что ответ был удачным?

2023-03-18 12:22 UTC, merged