Added likes and additions to friends, there are questions about the a…
Kaminari26/java-filmorate pull request #13
Opened 2023-03-23 11:00 UTC by Kaminari26

…rchitecture, I could not solve it myself

2023-03-23 12:42 UTC, YazykovMikhail requested changes
Нехватает реализации пенукта "Убедитесь, что ваше приложение возвращает корректные HTTP-кодов' - добавь класс ErrorHandler

Так же у тебя есть папка в проекте validationExeption - пакеты пишутся только с маленькой. Назови ее лучше exception

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likeList = new HashSet<>();
Все таки логичнее когда идет первым id, хотя это и не принципиально.
Но красивее и привычнее если поле id будет стоить ан первом месте. 

и так же добавь анноатция @JsonIgnore что бы нельзя было передать это поле.

likeList - в названиях переменных не указывай тип переменной
likes, или userIds

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
можно добавить @NotNull

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +    InMemoryFilmStorage inMemoryFilmStorage = new InMemoryFilmStorage();
Повтори еще раз как работает @Autowired и как ей пользоваться
поле InMemoryFilmStorage inMemoryFilmStorage = new InMemoryFilmStorage(); обьявлять тут не нужно

так, опять проблема с подификторами доступа.
Любое обьявление переменной начинается с модификатора доступа

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +@RequiredArgsConstructor
можно испольовать, если ты понимаешь как это рабоатет под капотом, но если непонимашеь
используй констурктор и аннотацию @Autowired

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
>  @Slf4j
У тебя в контроллерх нет логирования, но оно должно быть
- пришел запрос: тело запроса
- отправлен овте: тело ответа

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
>          }
разметка

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
>              return user;
ты возвращаешь юзера не которого обновил, а который пришел в запросе. 
Юзер после обновления находится вот тут 
User updatedUser = inMemoryUserStorage.update(user);

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/FilmController.java
> +    FilmService filmService = new FilmService(inMemoryFilmStorage);
FilmService filmService;  - повтори как работает  @Autowired и используй ее

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/сontroller/UserController.java
> +    InMemoryUserStorage inMemoryUserStorage = new InMemoryUserStorage();
Замечания аналогичны FilmController

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    InMemoryFilmStorage inMemoryFilmStorage;
Разберись как работает и как использовать  @Autowired

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +     InMemoryUserStorage inMemoryUserStorage;
Разберись как работает и как использовать @Autowired

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public HashMap<Long, Film> getFilmMap() {
этого метода тут не должно быть

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Boolean contains(Long id) {
этого метода тут не должно быть

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if(!contains(id)) {
Обращу еще ра внимание, тут просиодит поиск дважды сначало тут icontains(id)
потом filmMap.get(id), сделай что бы поиск был один раз. 
Найди все такие же моменты в коде и поправь это

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            log.warn("Фильм не найден");
log.error 
поправь везде где выбрасывается исключение

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        }else {
разметка

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if(!contains(id)) {
Когда можно не делать else лучше его не делать.
public User getById(Long id) {
        log.info("Запрошен пользователь с id " + id);
        User user = users.get(id);
        if(user == null) {
            log.error("Пользователь не найден");
            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        }
        log.info("Пользователь найден: {}", user);
        return user;
    }
    рассмотри этот код,  поищи похожие моменты и поправь

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isBlank()) {
это логика для сервиса, в сторадже просто общение с хранилищем и все. Вся логика должна быть в сервисе

2023-03-23 12:42 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +            user.setName(user.getLogin());
стоит добавить логирование, произошел какой то бизнес процесс, как потом об этом узнать

2023-03-23 12:51 UTC, YazykovMikhail requested changes

2023-03-23 12:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        log.info("Пользователь: "
еще никто никому не поставил, а ты уже залогировал. 
Плюс ты тут дедаешь поиск и потом еще в коде делаешь поиск. 

Такое происхордит в каждом методе, поправь везде

2023-03-23 12:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        if (!inMemoryFilmStorage.getFilmMap().containsKey(id)) {
в репозитории есть метод getById который и так вернет исклчбени если не найдет. А ты тут делаешь зачем то это проверка, пичем предварительно получив все все фильмы(а если их там 8765456789) и вызываешь метож .containsKey(id), но это не метод хранилища, это метод конкретной реализации(Мапы).
в inMemoryFilmStorage метода getFilmMap() не должно быть. Все методы всне зависимости от хранилища должны работать одинаково, для этого там и есть интерфейс.

2023-03-23 12:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        if (inMemoryFilmStorage.getFilmMap().get(id).getLikeList().equals(userId)) {
такое же замечние и тут

2023-03-23 12:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            log.info("Фильм найден");
разметка

2023-03-23 12:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    public User addFriends (Long id , Long friendId) {
кодстайл

2023-03-23 12:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        if(inMemoryUserStorage.getUsersMap().get(id) == null || inMemoryUserStorage.getUsersMap().get(friendId) == null){
код стайл

2023-03-23 12:51 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        log.warn("Пользователь не найден");
разметка

2023-03-23 16:52 UTC, Kaminari26 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends = new HashSet<>();
@JsonIgnore не получается использовать, тесты хотят получать айдишники

2023-03-25 10:22 UTC, YazykovMikhail requested changes
Уже лучше, но какие то комментарии не поправил и есть что еще поправить. 
Отмечай коментарии который поправил решенными. Что бы они не мешали и так будет лучше видно что ты поправил уже.

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +
Обрати внимание что все ршибки должны обрабаывать.

вот так будет лучше:
```
@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ErrorResponse handleNotFoundException(final DataNotFoundException e) {
		log.info("404 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}

	@ExceptionHandler
	@ResponseStatus(HttpStatus.BAD_REQUEST)
	public ErrorResponse handleValidationException(final ValidationException e) {
		log.info("400 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}

	@ExceptionHandler
	@ResponseStatus(HttpStatus.CONFLICT)
	public ErrorResponse handleAlreadyExistException(final DataAlreadyExistException e) {
		log.info("409 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}

	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}

```
	
Нужно будет сделать обьект ErrorResponse для овтетов:
public class ErrorResponse {
	private final String error;

	public ErrorResponse(String error) {
		this.error = error;
	}

	public String getError() {
		return error;
	}
}

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
сделай перенос строки между полями, стримись к единообразию

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    InMemoryUserStorage inMemoryUserStorage = new InMemoryUserStorage();
InMemoryUserStorage inMemoryUserStorage = new InMemoryUserStorage();
создават ьсамому не нужно обьект. Оставь это спрингу. 
Так же в качестве типа перемнной используй интерфейс там где это можно

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        } else {
Тут лучше не использовать else. будет читаемее

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        } else {
Тут лучше не использовать else. будет читаемее

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +    Boolean contains(Long id);
я бы убрал этот метод. 
Есть обьект или нет определяется что вернулось в get
обьект или null

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        {
код стайл

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if(!contains(id)) {
не поправил

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +
лишний перенос

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Boolean contains(Long id) {
этот меод не нужен

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage {
implements FilmStorage

и не забудь проставить     @Override
 надо методами

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    InMemoryFilmStorage inMemoryFilmStorage;
private final

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +@RequiredArgsConstructor
Используй если только понимаешь как это рабоатет с учетом спинга

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +     InMemoryUserStorage inMemoryUserStorage;
private final

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    InMemoryUserStorage inMemoryUserStorage = new InMemoryUserStorage();
private final

2023-03-25 10:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +@RequiredArgsConstructor
Используй если только понимаешь как это рабоатет с учетом спинга

2023-03-25 10:43 UTC, Kaminari26 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +
Я видимо не понял чего то, в моем варианте же оно работало, вроде бы, оно все равно требует контруктор?

2023-03-25 12:41 UTC, Kaminari26 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    InMemoryUserStorage inMemoryUserStorage = new InMemoryUserStorage();
не разобрался, методы везде отваливаются

2023-03-25 13:08 UTC, Kaminari26 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +@RequiredArgsConstructor
Если я начну использовать только то, что понимаю, то боюсь далеко от hello world не уйду)

2023-03-26 09:44 UTC, YazykovMikhail approved these changes
Комментарии который ты поправил отмечай решенными. И тебе будет проще смотреть только на новые и мне будет вижно что ты поправил, а что нет.

2023-03-26 09:44 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    public class ErrorResponse {
Вынеси этот класс отдельно

2023-03-26 09:44 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +      T add(T obj);
разметка

2023-03-26 11:57 UTC, merged