add database so hard second real
Kaminari26/java-filmorate pull request #15
Opened 2023-04-21 17:51 UTC by Kaminari26

2023-04-22 12:37 UTC, YazykovMikhail requested changes
Готова новая версия, возвращаю для обновления

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
private Set<Long> likes = new HashSet<>(); - больше будет тут не нужен, теперь для них есть отдельная бд и они хранятся там.
 А доступ до них есть по отдельынм эндпоинтам. 
 	@DeleteMapping("/films/{id}/like/{userId}")
и
	@PutMapping("/films/{id}/like/{userId}")

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
Так же боле     private Set<Long> friendsIds = new HashSet<>();
больше тут не нужно, для хранения есть отдельная бд и для управления есть отдельные эндпоинты

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmDbService.java
> +    FilmStorage filmStorage;
модификтаоры доступа

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreDbService.java
> +    GenreStorage genreStorage;
модификтаоры доступа

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreDbService.java
> +    public Collection<Genre> getAllGenres() {
просто getAll
мы вызываем метод у класса GenreDbService и так понятно что он вернет. 
Поправь это во всех классах.

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreDbService.java
> +    public Genre getGenreById(Long id) {
просто get будет лучше по сигнатуре метода и так понятно что по id

поправь это везде

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserDbService.java
> +    UserStorage userStorage;
модификтаоры доступа, Как ты их пропускаешь?) 
У тебя же в точно таком же сервисе они есть) 
Смотреть на свои/чужие реализации и повторять их - хорошая практика

2023-04-22 12:37 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserDbService.java
> +        String sql = "SELECT * FROM Users WHERE user_id IN (SELECT friends_id FROM FRIENDS_USER WHERE user_id = " + id + ")";
сервис ничего не знает какая БД используется, ему это не интересно, тут не должно быть никаких завязок на кокретную бд. Запрос нужно вынести в DbStorage

2023-04-22 13:19 UTC, YazykovMikhail requested changes
Получается должно быть стораджи для:
- Film
- Friend
- Genre
- Likes
- Mpa
- User

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      InMemoryFilmStorage inMemoryFilmStorage;
Куда делись все модификаторы доступа? Проставь во всем коде. 

Это работае тне так. Ты использешь или InMemoryFilmStorage или IFilmService. 
Тем более что в коде inMemoryFilmStorage вообще не используется. Убери его. 

Смысл в нескольких реализай в том что ты используешь или одну или другую. Использую один и тот же интерфейс, я тебе присылал картинку

Хотя наеврное ты просто забыл убрать это поле.

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mpa/MpaDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.Mpa;
пакеты называются с маленькой буквы

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Date movieBirthday = Date.valueOf(LocalDate.of(1895, 12, 28));
Storage не занимаются валидацией. Их дело работать с базой данных. 
Заниматься бизгес логикей задача сервиса. 
или можно сделать огарничение на самой БД. Тогда убдет проверяться автоматические при вставке/обновлении

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS FRIENDS_USER;
В фалйе README должна быть скинута ссылка на файл со схемой БД. И так что бы она отображалась. 
И что то я вообще невижу в проекте картинку со схемой БД

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +    release_date DATE NOT NULL,
нужно еще поле 
 rate        int,

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +    friendship BOOLEAN,
Если это для подтвеждение дружбы. То в финальном задании такого задания не было. Это было промежуточное задание во время обучения. Для финального задания это не нужно

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +    friends_id BIGINT,
friend_id

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                DataAccessException e) {
разметка

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return null;
не возвращай null выбрасывай свое ислюечние

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +
лишние переносы строк

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        int countAffectedRows = jdbcTemplate.update("UPDATE FILMS set name = ?, description = ?, release_date = ?, duration = ?,  mpa_id =? WHERE film_Id = ?",
Вынеси sql запрос в отедльную строку. И в jdbcTemplate.update подставляй перемнную

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +
лишний перенос

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +
лишний перенос

проверь во всем коде

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +
лишний перенос

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Collection<Film> getByQuery(String sqlQuery, @Nullable Object... params) {
Что это за запрос? и почему он в интерфейсе. Убери его их интерфейса

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film addLike(Long id, Long userId) {
Для лайков создай свою LikeDbStorage

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public String getRatingName(long id) {
не используется

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    @Override
Как можно использовать лайки для рейтинга. 

```
@Override
	public void addLike(long filmId, long userId) {
		String sqlQuery = "merge into LIKES (film_id, user_id) values (?, ?)";
		jdbcTemplate.update(sqlQuery, filmId, userId);
		updateRate(filmId);
	}

	private void updateRate(long filmId) {
		String sqlQuery = "update FILMS f set rate = (select count(l.user_id) from LIKES l where l.film_id = f.film_id)  where film_id = ?";
		jdbcTemplate.update(sqlQuery, filmId);
	}
```

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Set<Genre> getGenreSets(long id) {
У тебя есть GenreDbStorage, зачем это тут?
Возвращай фильмы без жанров. А потом из сервиса вызывай запрос в GenreDbStorage получай жанры и наполнях фильмы.

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                String sqlGenres = "INSERT INTO film_genre (film_id, genre_id) VALUES (?, ?)";
Для работы с жанрами у тебя есть отдельный класс. Возврщай от сюда фильмы без жанров, а потом в сервисе полуай жарны и фильмы ими.

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbStorage.java
> +public interface DbStorage<T> extends Storage<T> {
DbStorage - зачем это нужно?
это не нужно

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/MemoryStorage.java
> +public interface MemoryStorage<T> extends Storage<T> {
MemoryStorage - не нужне. 
getMap - метода не должно существовать. Я писал про это

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +public class GenreDbStorage implements GenreStorage {
У жанров есть методы только get и getAll

они не изменюятся в течении работы программы. Только те что заданы с начала.

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +
Еще можно иметь вот такой метод для заполнения фильмов жанрами:
```
@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(StorageData::getId).toArray());
	}
```
	
можешь использовать если разберешься. Или реализовать свою вариант

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mpa/MpaDbStorage.java
> +public class MpaDbStorage implements MpaStorage {
У Mpa методы только get и getAll 

они не изменюятся в течении работы программы. Только те что заданы с начала.

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +public class GenreDbStorage implements GenreStorage {
Так же методы называются get и getAll и так понятно что они возвращают, потому что вызываются у конкретного класса.

Как говорил поправь это везде

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public Collection<User> friendsList(Long id) {
не нужный метод

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public Collection<User> mutualFriends(Long id, Long otherId) {
getCommonFriends

и вынеси это в FriendDbStrage

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserDbService.java
> +    public Collection<User> friendsListUsers(Long id) {
public List<User> getFriends(long id) {
		final User user = storage.get(id);
		return friendStorage.getFriends(user.getId());
	}
Должна быть своя Storage для таблице friends 
Для каждой таблице свою strotage

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserDbService.java
> +    public Collection<User> mutualFriends(Long id, Long otherId) {
getCommonFriends

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserDbService.java
> +        return userStorage.mutualFriends(id, otherId);
getCommonFriends

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        checkUsers(id, friendId);
проверки в storage делать не нужно. Все проверки должны пройти до этого

2023-04-22 13:19 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public Collection<User> getByQuery(String sqlQuery, @Nullable Object... params) {
Это не нужно

2023-04-22 13:19 UTC, YazykovMikhail commented on src/test/java/ru/yandex/practicum/filmorate/tests/UserValidationsTests.java
тесты нужно сделать в соотвествии с заданием. Хотя бы для film или user

2023-04-22 14:22 UTC, Kaminari26 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserDbService.java
> +    UserStorage userStorage;
я уверен что у меня уникальность 100% была бы, потому что не слышал что у кого то похожая ситуация =D Так что ворую почти все у себя же, но криво)

2023-04-22 14:37 UTC, Kaminari26 commented on src/main/resources/schema.sql
> +    release_date DATE NOT NULL,
mpa_id BIGINT REFERENCES MPA (mpa_id) это же оно и есть, разве нет?

2023-04-22 20:38 UTC, Kaminari26 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Set<Genre> getGenreSets(long id) {
Попробовал более простым способом, надеюсь получится

2023-04-23 17:45 UTC, YazykovMikhail approved these changes
Очень много где не проставлены модификаторы дотсупа, хотя замечание такое было. 
И заменчание которые ты поправил отмечай "решенными", иначе и ты пропускаешь и я не вижу что ты поправил, а что нет.

2023-05-23 19:30 UTC, merged